steps:
  - name: gradle:jdk11
    entrypoint: gradle
    args:
      - 'build'
      - '-Pversion=$TAG_NAME'
    id: build-jar

  - name: gcr.io/cloud-builders/docker
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/$REPO_NAME'
      - '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'
      - '.'
    id: build-docker-image
    waitFor:
      - build-jar

  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME'
    id: push-docker-image
    waitFor:
      - build-docker-image

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - 'run'
      - '--filename=k8s/deployment.yaml'
      - '--image=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'
      - '--location=${_CLUSTER_ZONE}'
      - '--cluster=${_CLUSTER_NAME}'
    waitFor:
      - push-docker-image

substitutions:
  _CLUSTER_NAME: $PROJECT_ID
  _CLUSTER_ZONE: us-central1-c
  TAG_NAME: $SHORT_SHA

tags:
  - $REPO_NAME
